import path from 'path';
import chalk from 'chalk';
import ora from 'ora';
import fs from 'fs-extra';
import Anthropic from '@anthropic-ai/sdk';
import dotenv from 'dotenv';
import { readFileIfExists, findFiles, readPackageJson } from '../utils/fs.js';
import { detectProject } from '../detect/index.js';

interface GuardRule {
  category: string;
  rules: string[];
}

const FALLBACK_TEMPLATE = (config: {
  name: string;
  database: string;
  auth: string;
  styling: string;
  safeZones: string[];
  patterns: string[];
}): string => `# ${config.name} — AI Coding Rules

> Generated by [Launch Crate CLI](https://github.com/tjpinder/launchcrate-cli). Vibe code safely.

## Safe Zones — DO NOT MODIFY

These files contain critical infrastructure. Never edit, overwrite, or regenerate them:

${config.safeZones.map(z => `- \`${z}\``).join('\n')}

## Stack

- **Database**: ${config.database}
- **Auth**: ${config.auth}
- **Styling**: ${config.styling}

## Rules

### Authentication
- Every API route MUST have authentication unless explicitly public
- Use the existing auth pattern — do not create alternative auth flows
- Never bypass or weaken auth checks for convenience

### Database
${config.database === 'prisma' ? `- Use the Prisma client from the existing import path
- Never modify prisma/schema.prisma without explicit instruction
- Always use parameterized queries — never interpolate variables into raw SQL` :
config.database === 'drizzle' ? `- Use the Drizzle client from the existing import path
- Never modify the schema file without explicit instruction
- Use the query builder — never write raw SQL with string interpolation` :
config.database === 'raw-sql' ? `- Use parameterized queries with proper type bindings — NEVER concatenate strings into SQL
- Use the existing database connection helper — do not create new connection pools
- Always scope queries by workspaceId/tenantId for multi-tenant isolation` :
config.database === 'supabase' ? `- Use the Supabase client from the existing import path
- Always use .eq() filters for row-level security
- Never bypass RLS policies` :
`- Use the existing database access pattern
- Never concatenate user input into queries`}

### Security
- NEVER hardcode API keys, secrets, passwords, or tokens in source code
- Use environment variables via process.env for all credentials
- Validate all user input before processing
- Never expose error stack traces in API responses
- Use timing-safe comparison for secret/token validation

### Code Style
${config.patterns.length > 0 ? config.patterns.map(p => `- ${p}`).join('\n') : `- Follow existing code conventions in the project
- Match the import style used in existing files
- Match the error handling pattern used in existing routes`}

### File Creation
- Only create new files — never modify existing files unless explicitly asked
- Place new features in the appropriate directory structure
- Follow the existing naming conventions (file names, component names, route structure)

### Testing
- Do not delete or modify existing tests
- When creating new features, follow the existing test patterns if tests exist
`;

const AI_SYSTEM_PROMPT = `You are generating a CLAUDE.md file (AI coding rules) for a Next.js project. Analyze the provided project context and generate practical, specific rules that will prevent AI coding tools from breaking the project.

Rules should be:
1. SPECIFIC to this project — reference actual file paths, import patterns, and conventions
2. ACTIONABLE — "use X instead of Y", not vague guidance
3. PROTECTIVE — focused on preventing the most common AI coding mistakes
4. CONCISE — each rule is one clear sentence

Output a CLAUDE.md file in markdown. Include sections:
- Safe Zones (files that must never be modified)
- Architecture (how the project is structured)
- Database (how to query, what ORM, what patterns)
- Authentication (how auth works, what wrappers to use)
- Security (hardcoded secrets, input validation, etc.)
- Code Conventions (import style, naming, error handling)
- Common Mistakes (things AI tools frequently get wrong in this codebase)

Be practical and blunt. This file will be read by AI assistants that need clear boundaries.`;

export async function guardCommand(options: { format?: string }): Promise<void> {
  const projectRoot = process.cwd();

  dotenv.config({ path: path.join(projectRoot, '.env.local') });
  dotenv.config({ path: path.join(projectRoot, '.env') });

  const spinner = ora('Analyzing project...').start();

  // Detect project
  let config;
  try {
    config = await detectProject(projectRoot);
  } catch (error) {
    spinner.fail('Not a Next.js project');
    console.error(chalk.red(error instanceof Error ? error.message : String(error)));
    process.exit(1);
  }

  // Gather context for AI
  const referenceContents: { path: string; content: string }[] = [];
  for (const refPath of config.referenceFiles.slice(0, 4)) {
    const content = await readFileIfExists(path.join(projectRoot, refPath));
    if (content && content.length < 3000) {
      referenceContents.push({ path: refPath, content });
    }
  }

  // Check for existing CLAUDE.md or .cursorrules
  const existingClaude = await readFileIfExists(path.join(projectRoot, 'CLAUDE.md'));
  const existingCursor = await readFileIfExists(path.join(projectRoot, '.cursorrules'));

  // Detect code patterns
  const patterns = await detectPatterns(projectRoot, config);

  spinner.succeed('Project analyzed');

  // Check for conflicts
  const targets: { file: string; exists: boolean }[] = [
    { file: 'CLAUDE.md', exists: !!existingClaude },
  ];

  if (!options.format || options.format === 'all' || options.format === 'cursor') {
    targets.push({ file: '.cursorrules', exists: !!existingCursor });
  }

  const existingFiles = targets.filter(t => t.exists);
  if (existingFiles.length > 0) {
    spinner.stop();
    console.log(chalk.yellow(`\n  These files already exist:`));
    for (const f of existingFiles) {
      console.log(chalk.yellow(`    ${f.file}`));
    }

    const prompts = (await import('prompts')).default;
    const { overwrite } = await prompts({
      type: 'confirm',
      name: 'overwrite',
      message: 'Overwrite?',
      initial: false,
    });
    if (!overwrite) {
      console.log(chalk.yellow('Aborted.'));
      return;
    }
  }

  // Generate rules
  const apiKey = process.env.ANTHROPIC_API_KEY;
  let claudeContent: string;

  if (apiKey) {
    const genSpinner = ora('Generating AI safety rules...').start();
    try {
      claudeContent = await generateWithAI(apiKey, config, referenceContents, patterns);
      genSpinner.succeed('Generated AI safety rules');
    } catch (error) {
      genSpinner.warn('AI generation failed, using template');
      claudeContent = FALLBACK_TEMPLATE({
        name: config.project.name,
        database: config.stack.database,
        auth: config.stack.auth,
        styling: config.stack.styling,
        safeZones: config.safeZones,
        patterns,
      });
    }
  } else {
    claudeContent = FALLBACK_TEMPLATE({
      name: config.project.name,
      database: config.stack.database,
      auth: config.stack.auth,
      styling: config.stack.styling,
      safeZones: config.safeZones,
      patterns,
    });
  }

  // Write files
  await fs.writeFile(path.join(projectRoot, 'CLAUDE.md'), claudeContent, 'utf-8');
  console.log(chalk.green(`  + CLAUDE.md`));

  // Generate .cursorrules (same content, different filename)
  if (!options.format || options.format === 'all' || options.format === 'cursor') {
    await fs.writeFile(path.join(projectRoot, '.cursorrules'), claudeContent, 'utf-8');
    console.log(chalk.green(`  + .cursorrules`));
  }

  console.log('');
  console.log(chalk.bold('  AI safety rules generated.'));
  console.log(chalk.dim('  Commit these files so every AI session respects your architecture.'));
  console.log('');
}

async function generateWithAI(
  apiKey: string,
  config: Awaited<ReturnType<typeof detectProject>>,
  references: { path: string; content: string }[],
  patterns: string[]
): Promise<string> {
  const client = new Anthropic({ apiKey });

  let userPrompt = `## Project: ${config.project.name}
- Next.js ${config.project.frameworkVersion} (${config.project.router === 'app' ? 'App Router' : 'Pages Router'})
- Language: ${config.project.language}
- Database: ${config.stack.database}
- Auth: ${config.stack.auth}
- Styling: ${config.stack.styling}

## Safe Zones
${config.safeZones.map(z => `- ${z}`).join('\n')}

## Detected Code Patterns
${patterns.map(p => `- ${p}`).join('\n')}
`;

  if (references.length > 0) {
    userPrompt += `\n## Reference Files\n`;
    for (const ref of references) {
      userPrompt += `\n### ${ref.path}\n\`\`\`\n${ref.content}\n\`\`\`\n`;
    }
  }

  userPrompt += `\nGenerate the CLAUDE.md file now. Start with the project name as the heading.`;

  const response = await client.messages.create({
    model: 'claude-sonnet-4-5-20250514',
    max_tokens: 4096,
    system: AI_SYSTEM_PROMPT,
    messages: [{ role: 'user', content: userPrompt }],
  });

  const text = response.content
    .filter((block): block is Anthropic.TextBlock => block.type === 'text')
    .map(block => block.text)
    .join('');

  // Clean up any markdown code fences around the whole output
  return text.replace(/^```(?:markdown)?\n?/, '').replace(/\n?```$/, '');
}

async function detectPatterns(projectRoot: string, config: Awaited<ReturnType<typeof detectProject>>): Promise<string[]> {
  const patterns: string[] = [];

  // Check for common patterns by reading a few files
  for (const refPath of config.referenceFiles.slice(0, 3)) {
    const content = await readFileIfExists(path.join(projectRoot, refPath));
    if (!content) continue;

    // Import style
    if (content.includes("from '@/")) {
      patterns.push("Use '@/' path alias for imports (e.g., @/lib/db, @/components/ui)");
      break;
    } else if (content.includes("from '~/")) {
      patterns.push("Use '~/' path alias for imports");
      break;
    }
  }

  // Check for specific libraries
  const pkg = await readPackageJson(projectRoot);
  if (pkg) {
    const deps = { ...(pkg.dependencies as Record<string, string> || {}), ...(pkg.devDependencies as Record<string, string> || {}) };

    if (deps['zod']) patterns.push('Use Zod for input validation on all API routes');
    if (deps['react-hook-form']) patterns.push('Use react-hook-form for form state management');
    if (deps['@tanstack/react-query']) patterns.push('Use React Query for data fetching in client components');
    if (deps['swr']) patterns.push('Use SWR for data fetching in client components');
    if (deps['lucide-react']) patterns.push('Use lucide-react for icons');
    if (deps['@radix-ui/react-dialog'] || deps['@shadcn/ui']) patterns.push('Use shadcn/ui components from @/components/ui');
    if (deps['dompurify'] || deps['isomorphic-dompurify']) patterns.push('Sanitize HTML with DOMPurify before rendering');
  }

  return patterns;
}
